// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: mplpagkijabershebrzx

class SupabaseConfig {
  static const String supabaseUrl = 'https://mplpagkijabershebrzx.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wbHBhZ2tpamFiZXJzaGVicnp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0MjExMzcsImV4cCI6MjA3Njk5NzEzN30.TTvc3Sb1OLOOfCDA758DWz-XsOiY6bNRzUmaCQjZ0_4';
}
